"""onboarding fields + settings prefs

Revision ID: 6fe885597d87
Revises: 694fa1a7f87e
Create Date: 2026-06-21 15:41:14.333307
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6fe885597d87'
down_revision: str | None = '694fa1a7f87e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOT NULL columns get a server_default so the migration is safe on tables
    # that already hold rows (the ORM still supplies Python defaults for new rows).
    op.add_column(
        'user_settings',
        sa.Column('daily_target', sa.Integer(), nullable=False, server_default='3'),
    )
    op.add_column('user_settings', sa.Column('reminder_slot', sa.String(length=20), nullable=True))
    op.add_column(
        'users',
        sa.Column(
            'onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        'users',
        sa.Column('pact_accepted', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('users', sa.Column('focus_areas', sa.JSON(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'focus_areas')
    op.drop_column('users', 'pact_accepted')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('user_settings', 'reminder_slot')
    op.drop_column('user_settings', 'daily_target')
    # ### end Alembic commands ###
