"""add coach to user_settings

Revision ID: 96f9289dee1c
Revises: 6fe885597d87
Create Date: 2026-06-21 19:03:45.310098
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '96f9289dee1c'
down_revision: str | None = '6fe885597d87'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        'user_settings',
        sa.Column('coach', sa.String(length=20), nullable=False, server_default='atlas'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'coach')
    # ### end Alembic commands ###
